ApexBootcamp/force-app/main/default/objects/Onboarding_Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Session</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>VolunteerFx</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
            <value>
                <fullName>Aloha</fullName>
            </value>
            <value>
                <fullName>Services Org</fullName>
            </value>
            <value>
                <fullName>Slides</fullName>
            </value>
            <value>
                <fullName>Trailblazer</fullName>
            </value>
            <value>
                <fullName>Webassessor</fullName>
            </value>
            <value>
                <fullName>Quip</fullName>
            </value>
            <value>
                <fullName>Org62</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ApexBootcamp/force-app/main/default/classes/TriggerHandler.cls
public class TriggerHandler 
{
    //Activity Validation
    public void ValidateActivityPoints(List<Onboarding_Activity__c> activities) 
    {
        //Goes through every activity that got passed from Trigger.New
        for (Onboarding_Activity__c activity : activities) 
        {
            //Validates that if the activity type is Modules then it should have associated trailhead points
            if (activity.Type__c == 'Module' && (activity.Trailhead_Points__c == null || activity.Trailhead_Points__c == 0)) 
            {
                //Displays the validation error to the user
                activity.addError(activity.Name + ' is a Trailhead Module and requires Points > 0');
            }
        }
    }
}